import type { Metadata } from "next";
import { createClient } from "@/utils/supabase/server";
import { ProfileProvider } from "@/contexts/profileContext";
import { Profile, profileSelectorString } from "@/types/profile";

export const metadata: Metadata = {
  title: "Project 4",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const profile = await getProfile();

  return (
    <html lang="en">
      <body>
        <ProfileProvider profile={profile}>
          {children}
        </ProfileProvider>
      </body>
    </html>
  );
}

async function getProfile(): Promise<Profile | null> {
  const supabase = await createClient();
  const user = await supabase.auth.getUser();

  if (!user || !user.data.user) {
    return null;
  }

  const { data } = await supabase
    .from("profiles")
    .select(profileSelectorString)
    .eq("id", user.data.user.id);

  const profile = data?.[0];

  // SAFE for Client Components
  return profile ? JSON.parse(JSON.stringify(profile)) : null;
}

